DROP TABLE IF EXISTS subscription_history;
DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS channel;

-- Create Table
CREATE TABLE member (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    subscription_status ENUM('NONE', 'BASIC', 'PREMIUM') NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE channel (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(100) NOT NULL,
     type ENUM('FULL_ACCESS', 'SUBSCRIBE_ONLY', 'UNSUBSCRIBE_ONLY') NOT NULL,
     created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE subscription_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    action_type ENUM('SUBSCRIBE', 'UNSUBSCRIBE') NOT NULL,
    status ENUM('NONE', 'BASIC', 'PREMIUM') NOT NULL,
    action_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES member(id),
    FOREIGN KEY (channel_id) REFERENCES channel(id)
);

-- Insert Member Rows
INSERT INTO member (phone_number, subscription_status) VALUES
('01011111111', 'NONE'),
('01022222222', 'BASIC'),
('01033333333', 'PREMIUM'),
('01044444444', 'PREMIUM');

-- Insert Channel Rows
INSERT INTO channel (name, type) VALUES
('1_FULL_ACCESS_CHANNEL', 'FULL_ACCESS'),
('2_SUBSCRIBE_ONLY_CHANNEL', 'SUBSCRIBE_ONLY'),
('3_UNSUBSCRIBE_ONLY_CHANNEL', 'UNSUBSCRIBE_ONLY');

-- 기존 멤버에 대한 구독 이력 추가
INSERT INTO subscription_history (member_id, channel_id, action_type, status, action_date) VALUES
(4, 1, 'SUBSCRIBE', 'BASIC', '2024-08-01 10:00:00'),
(4, 2, 'SUBSCRIBE', 'BASIC', '2024-08-02 11:00:00'),
(4, 1, 'UNSUBSCRIBE', 'NONE', '2024-08-03 12:00:00'),
(4, 3, 'SUBSCRIBE', 'PREMIUM', '2024-08-04 13:00:00'),
(4, 2, 'UNSUBSCRIBE', 'BASIC', '2024-08-05 14:00:00'),
(4, 1, 'SUBSCRIBE', 'PREMIUM', '2024-08-06 15:00:00'),
(4, 2, 'SUBSCRIBE', 'PREMIUM', '2024-08-07 16:00:00'),
(4, 3, 'UNSUBSCRIBE', 'BASIC', '2024-08-08 17:00:00'),
(4, 1, 'UNSUBSCRIBE', 'BASIC', '2024-08-09 18:00:00'),
(4, 2, 'UNSUBSCRIBE', 'NONE', '2024-08-10 19:00:00');


